server.port=1085
spring.application.name=vendedor-service
spring.datasource.url=jdbc:oracle:thin:@bd2_medium
spring.datasource.username=ADMIN
spring.datasource.password=Arlette*2003
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1