spring.application.name=carrito
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@bd2_high?TNS_ADMIN=D:\Nueva carpeta (15)\TiendaTodo (1)\TiendaTodo\Wallet

spring.datasource.username=ADMIN

spring.datasource.password= Arlette*2003

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate=DEBUG

logging.level.com.zaxxer.hikari=DEBUG

logging.level.java.sql=DEBUG

server.port=1080
